app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /admin

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
